name: release
on:
    push:
        tags:
            - 'v*.*.*'
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout source
              uses: actions/checkout@v3

            - name: Install poetry
              run: pipx install poetry==2.1.1

            - name: Setup python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.11'
                  cache: 'poetry'

            - name: Configure poetry
              run: |
                poetry self add "poetry-dynamic-versioning[plugin]"
                poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}

            - name: Build package
              run: poetry build

            - name: Publish to PyPI
              run: poetry publish
